name: Application Bug Report
description: Report related to the Rich Presence Plus application
labels: ["bug", "application"]

body:
  - type: markdown
    attributes:
      value: |
        Please verify that your bug hasn't been reported before submitting a new issue. If it has, kindly respond to the existing issue.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a detailed sequence of actions that should be taken to reproduce the bug.
      placeholder: |
        1. Open...
        2. See...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe the outcome you expected to see.
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
      description: What version of Rich Presence Plus are you running?
      placeholder: v0.0.3-stable
    validations:
      required: true
  - type: input
    id: default-browser
    attributes:
      label: Default Browser
      description: What is your default browser?"
      placeholder: Google Chrome 132.0.6779.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Please provide the operating system you are using.
      placeholder: Windows 11 Pro 23H2
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
  - type: textarea
    id: a-comments
    attributes:
      label: Additional comments
  - type: textarea
    id: logfile
    attributes:
      label: App log
      description: Please attach the application log.
      placeholder: rpp.log
    validations:
      required: true
